Target: repair the build for `-Werror=maybe-uninitialized`
When building with GCC 9.3, the following maybe uninitialized path is identified:

~~~
Sources/Target/Linux/Process.cpp: In member function ‘virtual ds2::ErrorCode ds2::Target::Linux::Process::wait()’:
Sources/Target/Linux/Process.cpp:328:51: error: ‘tid’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  328 |   if (!(WIFEXITED(status) || WIFSIGNALED(status)) || tid != _pid) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
~~~

Although the `DS2ASSERT` exists above the loop, gcc does not propagate the
information through LICM which results in the path being misflagged.  Convert to
`do { } while` instead of `while { }` to indicate that we expect at least one
iteration through the loop.